### ISSUE TITLE
Brotli: "Uncaught Corrupted reserve bit"

### ISSUE THREAD

**Issue by LewisTehMinerz** [libass/JavascriptSubtitlesOctopus#142]
I'm attempting to use a freshly compressed Brotli file, however the worker reports that it is corrupt, which makes no sense since I can decompress it completely fine using the reference Python implementation of Brotli. This issue also occurs for me with the example `.br` files that are in the GitHub pages site.

I recompressed the `aot3p2_op.ass` file that was provided as an example to test if it would still work. The original file works fine, but is slow to load, hence my attempts at compression.

Here is my resulting `.br` file: [aot3p2_op.ass.br.gz](https://github.com/libass/JavascriptSubtitlesOctopus/files/8931556/aot3p2_op.ass.br.gz)
 
![](https://discord.coffee/mzHxBp1.png)

**Comment by TheOneric** [comment]
Works for me with JSO locally built from master. For reference the brotli-compressed file you attached has SHA256 `5ad4409eca1200bc0726ad50ec1801b0d042cccc9aac3a5e48bf1242e4b630ed`.
What version of JSO are you testing with? If it isn't the latests nightly *(see GitHub Action Artifacts while logged in)*, test again with that.

**Comment by LewisTehMinerz** [comment]
I am using latest nightly. Just redownloaded it, put it in, and got the exact same result.

**Comment by LewisTehMinerz** [comment]
And on further investigation, it appears that it's because my development web server returns the file with `Content-Encoding: br` (which is to be expected), and Chrome automatically decompresses it before serving it off to wherever (in this case JSO). Because JSO's check is [only checking for .br](https://github.com/libass/JavascriptSubtitlesOctopus/blob/18a53fdb77700c4bfc170a50b63b3c4044fc91b7/src/pre-worker.js#L48), this causes it to try and read the plaintext version as Brotli which is incorrect. Forcing it to `false` allows me to use the Brotli version fine.

I assume you're using something like Firefox? I'm not sure if that will automatically decompress Brotli.

**Comment by TheOneric** [comment]
Good work, identifying the root cause :)

> And on further investigation, it appears that it's because my development web server returns the file with `Content-Encoding: br` (which is to be expected), and Chrome automatically decompresses it before serving it

This is not necessarily expected behaviour. `Content-Encoding` documents what encoding the original payload has been altered with. If you put a `.br` file on your server the original payload technically is the brotli-compressed file itself and `Content-Encoding` should not be set (unless a further compression was applied on the fly). Ofc, sometimes you might want to have it automatically decompressed, if e.g. the file is a cached pre-compressed version of the original, but that’s a special case.
Look for example at the doubly compressed `aot3p2_op.ass.br.gz` you attached. It is gzip-compressed, yet GitHub’s server don't and in general arguably shouldn't automatically set `Content-Encoding: gzip` *(resulting in downloaders getting just `aot3p2_op.ass.br` but with a misleading `*.gz` name)*. Imagine GH would accept brotli-compressed files for uploads, and you tried to upload your faulty `*.ass.br` sample, but at downloads everyone else would just get uncompressed ASS (with a `*.br` name) — or nothing and an error in case the compression was actually faulty.

As you mentioned, detecting brotli is hard, so not a viable approach for JSO. If you want to let JSO handle the brotli-decompression, your server must treat `*.br` files as the original payload, i.e. not automatically set `Content-Encoding: br`.
Alternatively, you an let the server and browser handle (de)compression. JSO would just see `*.ass` but the server could actually transfer the content gzip- or brotli-compressed with the browser performing decompression.

> I assume you're using something like Firefox? I'm not sure if that will automatically decompress Brotli.

Firefox afaik should if the header were set. The simple python server I use for testing doesn't auto set `Content-Encoding`. Neither does the server used for GitHub pages for our [example brotli file](https://libass.github.io/JavascriptSubtitlesOctopus/brotliSubTest.html?renderMode=lossy).

**Comment by LewisTehMinerz** [comment]
> This is not necessarily expected behaviour. Content-Encoding documents what encoding the original payload has been altered with. If you put a .br file on your server the original payload technically is the brotli-compressed file itself and Content-Encoding should not be set (unless a further compression was applied on the fly).

Sorry, yes, this is correct, I meant it was expected behaviour for my dev server since it passes `.br` down as if it was on-the-fly encoded. My apologies.

But yes, it just seems to be a quirk with the dev server itself rather than JSO. I've actually just learnt this isn't meant to be how the server responds with data, although I suppose it's not the worst thing in the world. Is there any performance improvement of `.br` directly vs on-the-fly with JSO?

**Comment by TheOneric** [comment]
> Is there any performance improvement of .br directly vs on-the-fly with JSO?

Since JSO currentl uncompresses brotli in JS (migrating it to WASM would be possible), letting Server and Browser handle (de)compression transparently is likely a bit better performance wise. However, that depends on the Browser supporting brotli compression *(not sure if all "SmartTV" browser do)* and configuring the server appropriately. Which approach is more suitable depends on your usecase.
