### ISSUE TITLE
There is a problem with subtitles jumping when using Arabic

### ISSUE THREAD

**Issue by chenyangxx** [libass/JavascriptSubtitlesOctopus#163]
There is a problem with subtitles jumping when using Arabic，There is no problem when using other languages.
This is the test ass file，thanks...

https://github.com/libass/JavascriptSubtitlesOctopus/assets/16031348/4722e074-10ec-4c5f-8997-31dbe62ec1e5

[test_ass.txt](https://github.com/libass/JavascriptSubtitlesOctopus/files/13335536/test_ass.txt)

**Comment by TheOneric** [comment]
This is expected behaviour and comes from BiDi being run on each glyph run in ASS.

Glyph run split occur e.g. on colour changes.
Your file uses `{\1c&HFFFFFF&}` and `{\1c&HFF0000&}` override blocks after each sequence, even if the block just resets the current colour again — however such "noop" blocks do *not* induce run-splits.  
Thus as the red colour moves, so does the way glyph runs are split change and thus the bidi positioning.

To get consistent results, you’ll need to ensure the bidi runs are the same for all variants. For this you can either
   1. insert a Left-to-right mark (Unicode Codepoint `U+200E`) **after** each override block. Explicit LTR and RTL marks will insert splits into the bidi layout (but won't cause general ASS glyph runs)
   2. if there is some prperty you do not actually use in the subtitles, here e.g. the secondary colour `\2c`, you can toggle this to a different value inside each override tag to cause ASS glyph run splits

The first approach works regardless of which style properties are used and can be easily automated (if the file is being generated). However, depending on your editor the LTR marks might be invisible which might be confusing when manually editing the file.

Here is your testfile with both of the approaches implemented:
  1. [octo163_ltrAfterBlock.txt](https://github.com/libass/JavascriptSubtitlesOctopus/files/13481778/octo163_ltr-onlyAfterBlock.txt)
  2.  [octo163_c2.txt](https://github.com/libass/JavascriptSubtitlesOctopus/files/13481783/octo163_c2.txt)

and a screenshot of how the LTR marks are placed from an editor which displays them (vim):
![editor_showing_ltr-mark](https://github.com/libass/JavascriptSubtitlesOctopus/assets/1668471/5b58c406-d84d-4572-a985-f1b484a783ea)

**Comment by chenyangxx** [comment]
This is the automatic reply message from the QQ mailbox.Hello, your email has been received, I will reply to you as soon as possible. Good Time!  Alex
